modLoader = "javafml" #mandatory
loaderVersion = "[36,)"
license = "All rights reserved"
issueTrackerURL = "${mod_issues_link}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_display_name}"
displayURL="${mod_website_link}"
logoFile = "icon.png"
credits = ""
authors = "mcrobertx22"
description = '''
Turns Minecraft into a hack and slash RPG!
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.mmorpg]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.mmorpg]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.mmorpg]]
modId = "library_of_exile"
mandatory = true
versionRange = "[1.5.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.mmorpg]]
modId = "curios"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.mmorpg]]
modId = "playeranimator"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"